### ISSUE TITLE
good

### ISSUE THREAD

**Issue by dcy0701** [Namitor/Shooooty#1]
<strong style="color:red;">请问下 弹幕是实时的？用户发送到另外一个人看到需要多久？</strong>

**Comment by JayveeHe** [comment]
基本上是实时的，现在是服务器收集10秒内的弹幕，然后按照时间间隔在用户端显示出来，所以最多有10秒的延迟。

**Comment by dcy0701** [comment]
使用的websocket协议吗？普通http协议应该不会有这样的效果。

**Comment by JayveeHe** [comment]
嗯，一开始我们也想到了websocket，不过后面为了测试图方便就使用了轮询的方法，然后就没怎么改了。
使用websocket的话的确会更加高效，我们也在考虑转向这一方式。
